# Generated by Django 4.2.3 on 2023-12-25 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0002_alter_employer_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='about',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='website',
        ),
    ]
