# Generated by Django 4.2.3 on 2023-12-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0003_remove_employer_about_remove_employer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employer',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
