# Generated by Django 4.2.3 on 2023-12-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0007_alter_employer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='photo',
            field=models.ImageField(blank=True, upload_to='employer'),
        ),
    ]
