# Generated by Django 4.2.3 on 2024-01-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0005_alter_joblistings_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblistings',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
