# Generated by Django 4.2.3 on 2024-01-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joblistings', '0006_joblistings_company_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblistings',
            name='is_featured',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
