# Generated by Django 4.2.3 on 2024-01-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeupload', '0002_resume_file_submitted_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
