# Generated by Django 4.2.3 on 2024-01-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeupload', '0003_resume_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
